# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  hugoUrl: https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_extended_0.57.2_Linux-64bit.tar.gz
  hugoTar: /tmp/hugo.tgz

steps:
- script: |
    wget -q -O $(hugoTar) $(hugoUrl)
    tar xzvf $(hugoTar)
    sudo rsync -av hugo /usr/local/bin/
  displayName: 'Install Hugo'
- script: |
    rm -r themes
    git clone https://github.com/umemak/inkblotty.git themes/inkblotty
  displayName: 'Install theme'
- script: |
    hugo version
    hugo
  displayName: 'Build Hugo Blog'
- script: |
    git config --global user.email "umematsu@gmail.com"
    git config --global user.name "Azure Pipeline"
    git clone https://$(github.username):$(github.token)@github.com/umemak/umemak.github.io.git /tmp/blog
    rm -rf /tmp/blog/blog
    rsync -av blog /tmp/blog/
    cd /tmp/blog
    mv public/blog blog
    mkdir public
    touch public/.keep
    git add .
    git commit -m 'Autocommit from $(Build.DefinitionName) $(Build.BuildNumber) ***NO_CI***'
    git push origin
  displayName: 'Commit to umemak.github.io'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
